package org.tai.fpl.gameweek;

public class GameweekNameFormatter {

    public static String formatName(String name) {

        /* Temporary fix */
        if (name.contains("Thiago Alc")) {
            name = "Thiago Alcantara";
        }

        return switch (name) {
            case "Adama Traoré Diarra" -> "Adama Traoré";
            case "Adrián San Miguel del Castillo" -> "Adrián";
            case "Ahmed El Mohamady" -> "Ahmed Elmohamady";
            case "Ahmed El-Sayed Hegazy" -> "Ahmed Hegazi";
            case "Alejandro Garnacho Ferreyra" -> "Alejandro Garnacho";
            case "Alexandre Moreno Lopera" -> "Álex Moreno";
            case "Alex Nicolao Telles" -> "Alex Telles";
            case "Alisson Ramses Becker" -> "Alisson";
            case "Allan Marques Loureiro" -> "Allan";
            case "André Filipe Tavares Gomes" -> "André Gomes";
            case "Andreas Hoelgebaum Pereira", "Andreas  Pereira" -> "Andreas Pereira";
            case "Antony Matheus dos Santos" -> "Antony";
            case "Arnaut Danjuma Groeneveld" -> "Arnaut Danjuma";
            case "Bamidele Alli" -> "Dele Alli";
            case "Benjamin Chilwell" -> "Ben Chilwell";
            case "Benjamin White" -> "Ben White";
            case "Bernard Anício Caldeira Duarte", "Bernard AnÃcio Caldeira Duarte" -> "Bernard";
            case "Bernardo Fernandes da Silva Junior" -> "Bernardo";
            case "Bernardo Mota Veiga de Carvalho e Silva", "Bernardo Veiga de Carvalho e Silva" -> "Bernardo Silva";
            case "Bjorn Engels" -> "Björn Engels";
            case "Bobby De Cordova-Reid", "Bobby Decordova-Reid" -> "Bobby Reid";
            case "Borja González Tomás", "Borja GonzÃ¡lez TomÃ¡s" -> "Borja Bastón";
            case "Bruno André Cavaco Jordão", "Bruno Jordao" -> "Bruno Jordão";
            case "Bruno Borges Fernandes", "Bruno Miguel Borges Fernandes" -> "Bruno Fernandes";
            case "Bruno Guimarães Rodriguez Moura" -> "Bruno Guimarães";
            case "Carlos Henrique Casimiro" -> "Casemiro";
            case "Carlos Ribeiro Dias" -> "Cafú";
            case "Carlos Vinícius Alves Morais", "Carlos Vinicius Alves Morais" -> "Carlos Vinícius";
            case "Cédric Alves Soares" -> "Cédric Soares";
            case "Conrad Egan-Riley" -> "CJ Egan-Riley";
            case "Cristiano Ronaldo dos Santos Aveiro" -> "Cristiano Ronaldo";
            case "Daniel Castelo Podence" -> "Daniel Podence";
            case "Daniel Ceballos Fernández" -> "Dani Ceballos";
            case "Danilo dos Santos de Oliveira" -> "Danilo";
            case "Darwin Núñez Ribeiro" -> "Darwin Núñez";
            case "David De Gea Quintana" -> "David de Gea";
            case "David Luiz Moreira Marinho" -> "David Luiz";
            case "David Raya Martin" -> "David Raya";
            case "Diego Carlos Santos Silva" -> "Diego Carlos";
            case "Diego Da Silva Costa" -> "Diego Costa";
            case "Diogo Dalot Teixeira", "José Diogo Dalot Teixeira" -> "Diogo Dalot";
            case "Diogo Teixeira da Silva" -> "Diogo Jota";
            case "Douglas Luiz Soares de Paulo" -> "Douglas Luiz";
            case "Ederson Santana de Moraes" -> "Ederson";
            case "Edward Nketiah" -> "Eddie Nketiah";
            case "Emerson Aparecido Leite de Souza Junior", "Emerson Leite de Souza Junior" -> "Emerson Royal";
            case "Emerson Palmieri dos Santos" -> "Emerson";
            case "Emiliano Buendía Stati" -> "Emiliano Buendía";
            case "Emiliano Martínez Romero" -> "Emiliano Martínez";
            case "Fábio Freitas Gouveia Carvalho", "Fabio Carvalho" -> "Fábio Carvalho";
            case "Fábio Ferreira Vieira" -> "Fábio Vieira";
            case "Fabio Henrique Tavares" -> "Fabinho";
            case "Facundo Pellistri Rebollo" -> "Facundo Pellistri";
            case "Felipe Anderson Pereira Gomes" -> "Felipe Anderson";
            case "Felipe Augusto de Almeida Monteiro" -> "Felipe";
            case "Fernando Luiz Rosa" -> "Fernandinho";
            case "Francisco Casilla Cortés" -> "Kiko Casilla";
            case "Francisco Femenía Far" -> "Kiko Femenía";
            case "Francisco Jorge Tomás Oliveira" -> "Chiquinho";
            case "Francisco Machado Mota de Castro Trincão" -> "Francisco Trincão";
            case "Frederico Rodrigues de Paula Santos" -> "Fred";
            case "Gabriel dos Santos Magalhães", "Gabriel Magalhães" -> "Gabriel";
            case "Gabriel Fernando de Jesus" -> "Gabriel Jesus";
            case "Gabriel Martinelli Silva", "Gabriel Teodoro Martinelli Silva" -> "Gabriel Martinelli";
            case "Gonçalo Manuel Ganchinho Guedes" -> "Gonçalo Guedes";
            case "Halil DerviÅŸoÄŸlu" -> "Halil Dervişoğlu";
            case "Gustavo Henrique Furtado Scarpa" -> "Gustavo Scarpa";
            case "Héctor Junior Firpo Adames", "Junior Firpo Adames" -> "Junior Firpo";
            case "Hee-Chan Hwang" -> "Hwang Hee-chan";
            case "Hélder Wander Sousa de Azevedo e Costa" -> "Hélder Costa";
            case "Heung-Min Son", "Son Heung-min" -> "Son Heung-Min";
            case "Hugo Bueno López" -> "Hugo Bueno";
            case "Ian Carlo Poveda-Ocampo" -> "Ian Poveda-Ocampo";
            case "Isaac Success Ajayi" -> "Isaac Success";
            case "Ismaila Sarr" -> "Ismaïla Sarr";
            case "Ivan Ricardo Neves Abreu Cavaleiro" -> "Ivan Cavaleiro";
            case "Javier Manquillo GaitÃ¡n", "Javier Manquillo Gaitán" -> "Javier Manquillo";
            case "Javier Hernández Balcázar" -> "Javier Hernández";
            case "Jefferson Lerma Solís" -> "Jefferson Lerma";
            case "Jeremy Sarmiento Morante" -> "Jeremy Sarmiento";
            case "Jesús Vallejo Lázaro" -> "Jesús Vallejo";
            case "João Félix Sequeira" -> "João Félix";
            case "João Filipe Iria Santos Moutinho" -> "João Moutinho";
            case "João Palhinha Gonçalves" -> "João Palhinha";
            case "João Pedro Cavaco Cancelo" -> "João Cancelo";
            case "João Pedro Junqueira de Jesus" -> "João Pedro";
            case "João Victor Gomes da Silva" -> "João Gomes";
            case "Joelinton Cássio Apolinário de Lira" -> "Joelinton";
            case "Jonathan Castro Otto" -> "Jonny";
            case "Jorge Luiz Frello Filho" -> "Jorginho";
            case "José Ángel Esmorís Tasende" -> "Angeliño";
            case "José Ignacio Peleteiro Ramallo", "JosÃ© Ignacio Peleteiro Romallo" -> "Jota";
            case "José Malheiro de Sá" -> "José Sá";
            case "Joseph Willock" -> "Joe Willock";
            case "Juan Camilo Hernández Suárez" -> "Juan Camilo Hernández";
            case "Juan Larios LÃ³pez", "Juan Larios López" -> "Juan Larios";
            case "Kayky da Silva Chagas" -> "Kayky";
            case "Lucas Rodrigues Moura da Silva" -> "Lucas Moura";
            case "Lucas Tolentino Coelho de Lima" -> "Lucas Paquetá";
            case "Luis Sinisterra Lucumí" -> "Luis Sinisterra";
            case "Lyanco Evangelista Silveira Neves Vojnovic", "Lyanco Silveira Neves Vojnovic" -> "Lyanco";
            case "Mads Roerslev Rasmussen" -> "Mads Roerslev";
            case "Marc Cucurella Saseta" -> "Marc Cucurella";
            case "Marc Roca Junqué" -> "Marc Roca";
            case "Mahmoud Ahmed Ibrahim Hassan" -> "Trézéguet";
            case "Marcus Oliveira Alencar" -> "Marquinhos";
            case "Mateo Joseph Fernández" -> "Mateo Joseph";
            case "Mateus Cardoso Lemos Martins" -> "Tetê";
            case "Matheus Luiz Nunes" -> "Matheus Nunes";
            case "Matheus Santos Carneiro Da Cunha" -> "Matheus Cunha";
            case "Mathias Jorgensen" -> "Mathias Jørgensen";
            case "Mathew Ryan" -> "Mat Ryan";
            case "Matthew Cash" -> "Matty Cash";
            case "Maximillian Aarons" -> "Max Aarons";
            case "Miguel Almirón Rejala" -> "Miguel Almirón";
            case "Mohamed Naser El Sayed Elneny" -> "Mohamed Elneny";
            case "Moisés Caicedo Corozo" -> "Moisés Caicedo";
            case "Muhamed BeÅ¡iÄ‡" -> "Muhamed Bešić";
            case "Nélson Cabral Semedo" -> "Nélson Semedo";
            case "Norberto Murara Neto" -> "Neto";
            case "Nuno Varela Tavares" -> "Nuno Tavares";
            case "Oghenekaro Peter Etebo" -> "Oghenekaro Etebo";
            case "Oluwasemilogo Adesewo Ibidapo Ajayi" -> "Semi Ajayi";
            case "Oriol Romeu Vidal" -> "Oriol Romeu";
            case "Pablo Fornals Malla" -> "Pablo Fornals";
            case "Pablo Hernández Domínguez" -> "Pablo Hernández";
            case "Pedro Lomba Neto" -> "Pedro Neto";
            case "Pedro Rodríguez Ledesma" -> "Pedro";
            case "Pelenda Joshua Dasilva" -> "Josh Dasilva";
            case "Philippe Coutinho Correia" -> "Philippe Coutinho";
            case "Ralf Fahrmann" -> "Ralf Fährmann";
            case "Raphael Dias Belloli" -> "Raphinha";
            case "Rayan Ait Nouri" -> "Rayan Aït-Nouri";
            case "Renan Augusto Lodi dos Santos" -> "Renan Lodi";
            case "Richarlison de Andrade" -> "Richarlison";
            case "Robert Kenedy Nunes do Nascimento" -> "Kenedy";
            case "Roberto Jiménez Gago", "Roberto Jimenez Gago" -> "Roberto Jiménez";
            case "Rodrigo Moreno" -> "Rodrigo";
            case "Rúben da Silva Neves", "Rúben Diogo da Silva Neves" -> "Rúben Neves";
            case "Rúben Gato Alves Dias", "Rúben Santos Gato Alves Dias" -> "Rúben Dias";
            case "Rúben Gonçalo Silva Nascimento Vinagre", "Rúben Nascimento Vinagre" -> "Rúben Vinagre";
            case "Ricardo Barbosa Pereira", "Ricardo Domingos Barbosa Pereira" -> "Ricardo Pereira";
            case "Rodrigo Hernandez" -> "Rodri";
            case "Rui Pedro dos Santos Patrício" -> "Rui Patrício";
            case "Samir Caetano de Souza Santos" -> "Samir";
            case "Sokratis Papastathopoulos" -> "Sokratis";
            case "Sergi Canós Tenés", "Sergi CanÃ³s" -> "Sergi Canós";
            case "Solomon March" -> "Solly March";
            case "Sung-yueng Ki" -> "Ki Sung-yueng";
            case "Thiago Alcântara do Nascimento", "Thiago AlcÃ¡ntara do Nascimento" -> "Thiago Alcântara";
            case "Thiago Emiliano da Silva", "Thiago Thiago" -> "Thiago Silva";
            case "Tote António Gomes", "Toti António Gomes" -> "Toti";
            case "Vitor Ferreira" -> "Vitinha";
            case "Wesley Moraes" -> "Wesley";
            case "Willian Borges da Silva", "Willian Borges Da Silva" -> "Willian";
            case "Willian José da Silva", "Willian José Da Silva" -> "Willian José";
            default -> name;
        };
    }
}
