package org.tai.fpl.gameweek;

public class NameFormatter {

    public static String formatName(String name) {
        return switch (name) {
            case "Adama Traoré Diarra" -> "Adama Traoré";
            case "Ahmed El Mohamady" -> "Ahmed Elmohamady";
            case "Ahmed El-Sayed Hegazy" -> "Ahmed Hegazi";
            case "Alejandro Garnacho Ferreyra" -> "Alejandro Garnacho";
            case "Alex Nicolao Telles" -> "Alex Telles";
            case "Andreas Hoelgebaum Pereira" -> "Andreas  Pereira";
            case "Bamidele Alli" -> "Dele Alli";
            case "Benjamin Chilwell" -> "Ben Chilwell";
            case "Benjamin White" -> "Ben White";
            case "Bernardo Mota Veiga de Carvalho e Silva", "Bernardo Veiga de Carvalho e Silva" -> "Bernardo Silva";
            case "Bobby De Cordova-Reid", "Bobby Decordova-Reid" -> "Bobby Reid";
            case "Bruno Borges Fernandes", "Bruno Miguel Borges Fernandes" -> "Bruno Fernandes";
            case "Cédric Alves Soares" -> "Cédric Soares";
            case "Carlos Vinícius Alves Morais" -> "Carlos Vinícius";
            case "Conrad Egan-Riley" -> "CJ Egan-Riley";
            case "Cristiano Ronaldo dos Santos Aveiro" -> "Cristiano Ronaldo";
            case "Daniel Castelo Podence" -> "Daniel Podence";
            case "Daniel Ceballos Fernández" -> "Dani Ceballos";
            case "Darwin Núñez Ribeiro" -> "Darwin Núñez";
            case "David De Gea Quintana" -> "David de Gea";
            case "David Raya Martin" -> "David Raya";
            case "Diogo Dalot Teixeira", "José Diogo Dalot Teixeira" -> "Diogo Dalot";
            case "Edward Nketiah" -> "Eddie Nketiah";
            case "Emerson Aparecido Leite de Souza Junior", "Emerson Leite de Souza Junior" -> "Emerson Royal";
            case "Emiliano Buendía Stati" -> "Emiliano Buendía";
            case "Emiliano Martínez Romero" -> "Emiliano Martínez";
            case "Fábio Freitas Gouveia Carvalho" -> "Fábio Carvalho";
            case "Facundo Pellistri Rebollo" -> "Facundo Pellistri";
            case "Francisco Casilla Cortés" -> "Kiko Casilla";
            case "Francisco Femenía Far" -> "Kiko Femenía";
            case "Gabriel Fernando de Jesus" -> "Gabriel Jesus";
            case "Gabriel Martinelli Silva", "Gabriel Teodoro Martinelli Silva" -> "Gabriel Martinelli";
            case "Gonçalo Manuel Ganchinho Guedes" -> "Gonçalo Guedes";
            case "Gustavo Henrique Furtado Scarpa" -> "Gustavo Scarpa";
            case "Héctor Junior Firpo Adames", "Junior Firpo Adames" -> "Junior Firpo";
            case "Hélder Wander Sousa de Azevedo e Costa" -> "Hélder Costa";
            case "Heung-Min Son", "Son Heung-min" -> "Son Heung-Min";
            case "Hugo Bueno López" -> "Hugo Bueno";
            case "Ian Carlo Poveda-Ocampo" -> "Ian Poveda-Ocampo";
            case "Ivan Ricardo Neves Abreu Cavaleiro" -> "Ivan Cavaleiro";
            case "Javier Manquillo GaitÃ¡n" -> "Javier Manquillo";
            case "Jefferson Lerma Solís" -> "Jefferson Lerma";
            case "Jeremy Sarmiento Morante" -> "Jeremy Sarmiento";
            case "João Filipe Iria Santos Moutinho" -> "João Moutinho";
            case "João Palhinha Gonçalves" -> "João Palhinha";
            case "João Pedro Cavaco Cancelo" -> "João Cancelo";
            case "José Malheiro de Sá" -> "José Sá";
            case "Joseph Willock" -> "Joe Willock";
            case "Juan Camilo Hernández Suárez" -> "Juan Camilo Hernández";
            case "Juan Larios LÃ³pez" -> "Juan Larios";
            case "Lucas Tolentino Coelho de Lima" -> "Lucas Paquetá";
            case "Luis Sinisterra Lucumí" -> "Luis Sinisterra";
            case "Mads Roerslev Rasmussen" -> "Mads Roerslev";
            case "Marc Cucurella Saseta" -> "Marc Cucurella";
            case "Marc Roca Junqué" -> "Marc Roca";
            case "Mateus Cardoso Lemos Martins" -> "Tetê";
            case "Matheus Luiz Nunes" -> "Matheus Nunes";
            case "Matheus Santos Carneiro Da Cunha" -> "Matheus Cunha";
            case "Mathew Ryan" -> "Mat Ryan";
            case "Miguel Almirón Rejala" -> "Miguel Almirón";
            case "Mohamed Naser El Sayed Elneny" -> "Mohamed Elneny";
            case "Moisés Caicedo Corozo" -> "Moisés Caicedo";
            case "Nélson Cabral Semedo" -> "Nélson Semedo";
            case "Nuno Varela Tavares" -> "Nuno Tavares";
            case "Oghenekaro Peter Etebo" -> "Oghenekaro Etebo";
            case "Oluwasemilogo Adesewo Ibidapo Ajayi" -> "Semi Ajayi";
            case "Oriol Romeu Vidal" -> "Oriol Romeu";
            case "Pablo Fornals Malla" -> "Pablo Fornals";
            case "Pablo Hernández Domínguez" -> "Pablo Hernández";
            case "Pedro Lomba Neto" -> "Pedro Neto";
            case "Pelenda Joshua Dasilva" -> "Josh Dasilva";
            case "Philippe Coutinho Correia" -> "Philippe Coutinho";
            case "Rúben da Silva Neves", "Rúben Diogo da Silva Neves" -> "Rúben Neves";
            case "Rúben Gato Alves Dias", "Rúben Santos Gato Alves Dias" -> "Rúben Dias";
            case "Rúben Gonçalo Silva Nascimento Vinagre", "RÃºben Nascimento Vinagre" -> "Rúben Vinagre";
            case "Ricardo Barbosa Pereira", "Ricardo Domingos Barbosa Pereira" -> "Ricardo Pereira";
            case "Rodrigo Hernandez" -> "Rodri";
            case "Rui Pedro dos Santos Patrício" -> "Rui Patrício";
            case "Sergi Canós Tenés" -> "Sergi Canós";
            case "Solomon March" -> "Solly March";
            case "Thiago Alcântara do Nascimento" -> "Thiago Alcântara";
            case "Willian Borges da Silva", "Willian Borges Da Silva" -> "Willian";
            default -> name;
        };
    }
}
